### ISSUE TITLE
lvcreate runs out of disk space

### ISSUE THREAD

**Issue by abalage** [SUSE/dice#13]
This is what I tried to do in a Vagrant box *
KIWI was installed from Virtualization_Appliances_Builder repo (42.1)

The box itself has roughly 16GB of free disk space by default, therefore I shrinked the size of volumes in config.xml to 7 and 10GB (yepp, that's slightly bigger than 16GB).

My main question is, is that qemu image should be a stale file or will it be fully initialized during setup?

```
[ INFO    ]: 15:01:14 | Creating volume group systemVG
[ DEBUG   ]: 15:01:14 | EXEC: [vgremove --force systemVG]
[ DEBUG   ]: 15:01:14 | EXEC: [pvcreate /dev/mapper/loop0p2]
[ DEBUG   ]: 15:01:14 | EXEC: [vgcreate systemVG /dev/mapper/loop0p2]
[ INFO    ]: 15:01:14 | Creating volumes(ext4)
[ INFO    ]: 15:01:14 | --> volume root with 7168 MB
[ DEBUG   ]: 15:01:14 | EXEC: [lvcreate -L 7168 -n root systemVG]
[ DEBUG   ]: 15:01:15 | EXEC: [mkfs.ext4 /dev/systemVG/root]
[ INFO    ]: 15:01:17 | --> volume var with 10240 MB
[ DEBUG   ]: 15:01:17 | EXEC: [lvcreate -L 10240 -n var systemVG]
[ DEBUG   ]: 15:01:17 | EXEC: Failed with stderr:   Volume group "systemVG" has insufficient free space (1097 extents): 2560 required.
, stdout: (no output on stdout)
[ INFO    ]: 15:01:17 | Cleaning up VolumeManagerLVM instance
[ DEBUG   ]: 15:01:17 | EXEC: [mountpoint /tmp/kiwi_volumes.d1hhqj9m//]
[ ERROR   ]: 15:01:17 | KiwiCommandError: lvcreate: stderr:   Volume group "systemVG" has insufficient free space (1097 extents): 2560 required.
, stdout: (no output on stdout)
[ DEBUG   ]: 15:01:17 | EXEC: [rm -r -f /tmp/kiwi_volumes.d1hhqj9m]
[ DEBUG   ]: 15:01:17 | EXEC: [vgchange -an systemVG]
[ INFO    ]: 15:01:17 | Cleaning up BootImageKiwi instance
[ DEBUG   ]: 15:01:17 | EXEC: [rm -r -f /tmp/kiwi_build_20161202-13111-eb2kbw.dice/kiwi_boot_root.8h412mas]
[ DEBUG   ]: 15:01:17 | EXEC: Failed with stderr: rm: cannot remove ‘/tmp/kiwi_build_20161202-13111-eb2kbw.dice/kiwi_boot_root.8h412mas/var/lib/machines’: Operation not permitted
, stdout: (no output on stdout)
[ INFO    ]: 15:01:17 | Cleaning up Disk instance
[ DEBUG   ]: 15:01:17 | EXEC: [kpartx -s -d /dev/loop0]
[ INFO    ]: 15:01:17 | Cleaning up LoopDevice instance
[ DEBUG   ]: 15:01:17 | EXEC: [losetup -d /dev/loop0]
[ INFO    ]: 15:01:17 | Cleaning up BootImageKiwi instance
[ DEBUG   ]: 15:01:17 | EXEC: [rm -r -f /tmp/kiwi_build_20161202-13111-eb2kbw.dice/kiwi_boot_root.oqrt7dex]
Exception ignored in: <bound method BootImageKiwi.__del__ of <kiwi.boot.image.kiwi.BootImageKiwi object at 0x7f0046bc8048>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/kiwi/boot/image/base.py", line 282, in __del__
    Path.wipe(directory)
  File "/usr/lib/python3.4/site-packages/kiwi/path.py", line 75, in wipe
    ['rm', '-r', '-f', path]
  File "/usr/lib/python3.4/site-packages/kiwi/command.py", line 106, in run
    command[0], error.decode(), output.decode()
kiwi.exceptions.KiwiCommandError: rm: stderr: rm: cannot remove ‘/tmp/kiwi_build_20161202-13111-eb2kbw.dice/kiwi_boot_root.8h412mas/var/lib/machines’: Operation not permitted
, stdout: (no output on stdout)
```
Also what can be done with the temporary directories?
I could not remove them as root, immutable flag is not set, nothing in dmesg can be seen. Nothing keeps it open, though the VG is still present and I cannot remove it.

```
vagrant-openSUSE-Leap:/home/vagrant # vgs
  WARNING: Device for PV D3cjR0-bMu3-yNsY-TjKq-lLCX-V6I3-pPOQMU not found or rejected by a filter.
  VG       #PV #LV #SN Attr   VSize  VFree
  systemVG   1   1   0 wz-pn- 11.29g 4.29g
vagrant-openSUSE-Leap:/home/vagrant # vgremove -v systemVG
    Using volume group(s) on command line.
  WARNING: Device for PV D3cjR0-bMu3-yNsY-TjKq-lLCX-V6I3-pPOQMU not found or rejected by a filter.
    There are 1 physical volumes missing.
  WARNING: 1 physical volumes are currently missing from the system.
Do you really want to remove volume group "systemVG" containing 1 logical volumes? [y/n]: y
    Archiving volume group "systemVG" metadata (seqno 2).
    Releasing logical volume "root"
  Aborting vg_write: No metadata areas to write to!
vagrant-openSUSE-Leap:/home/vagrant # vgs
  WARNING: Device for PV D3cjR0-bMu3-yNsY-TjKq-lLCX-V6I3-pPOQMU not found or rejected by a filter.
  VG       #PV #LV #SN Attr   VSize  VFree
  systemVG   1   1   0 wz-pn- 11.29g 4.29g
```

Thanks a lot for your patience Marcus. :)
* https://atlas.hashicorp.com/opensuse/boxes/openSUSE-42.1-x86_64

**Comment by schaefi** [comment]
This one has been addressed in kiwi here: https://github.com/SUSE/kiwi/pull/210

I'll submit a new kiwi and will rebuild the container

**Comment by abalage** [comment]
Thanks!

Meanwhile I reduced the disk space requirements in config.xml just to see it fits into the available disk space but it still failed, just the number of extents changes.
I am looking forward to test the new release.

**Comment by schaefi** [comment]
Could you provide the systemdisk section here for me ? I would be interested in the size setup

**Comment by schaefi** [comment]
> My main question is, is that qemu image should be a stale file or will it be fully initialized during setup?

I haven't answered that question. So it depends on the image type you are using

* for the vmx type it will be a stateful image of the requires size. The usual target is to use this disk as the system disk and it is not going to be expected to change in geometry

* for the oem type it will be only of the size required to hold the data. The requested size will be reached on first boot by a repartition/resize process.

**Comment by abalage** [comment]
Here is the systemdisk section for vmx image type. This is the same I used in docker and Vagrant VM.

```
        <type image="vmx" primary="true" boot="vmxboot/rhel-07.0" format="vmdk" filesystem="ext4" kernelcmdline="rhgb" bootloader="grub2">
            <systemdisk name="systemVG">
                <volume name="root" size="6G" mountpoint="/"/>
                <volume name="var" size="7G" mountpoint="/var"/>
            </systemdisk>
            <machine arch="x86_64" memory="4096" ncpus="1" guestOS="centos-64" HWversion="4">
               <vmnic driver="e1000" interface="0" mode="bridged"/>
               <vmdisk controller="buslogic" id="0"/>
               <vmdvd  controller="ide" id="1"/>
            </machine>
        </type>
```

Also thanks for the clarification regarding the qemu image sizes.

**Comment by schaefi** [comment]
ok thanks I'll give this a try here on my system

**Comment by schaefi** [comment]
oh wait I see you specify the size for root. That should be done as follows:

```xml
<volume name="@root" size="6G"/>
```

The root volume is special because managed by kiwi and you can't set a custom name or mountpoint for it. The name of the root volume is always set to LVRoot. I will create a runtime check for the above setup

**Comment by schaefi** [comment]
a short test with the adapted setup worked for me. Also added the runtime check to avoid such situations in the future. I'll prepare for the release now and let you know when the submission is done and the new container ready for use

**Comment by schaefi** [comment]
The container image has been updated with the latest kiwi. If you update your image description as written above the build will work. if not you will run into a runtime error with a better explanation about the problem

**Comment by abalage** [comment]
Thanks! I will definitely test it.

**Comment by abalage** [comment]
Indeed this problem looks to be solved. Thank you for your help!
